enum ChatRequestType {
  socraticQuestion,
  mcQuestion,
  explainCodeQuestion,
  completeCodeQuestion,
  writeCodeQuestion,
  submitCode,
  mcqAnswer,
  requestHint,
  studentQuestion,
  explainAnswer,
  socraticFeedback,
  status,
  noResult,
}
