enum ChatRequestType {
  guidingQuestion,
  guidingAnswer,
  socraticQuestion,
  mcQuestion,
  explainCodeQuestion,
  completeCodeQuestion,
  writeCodeQuestion,
  submitCode,
  mcqAnswer,
  requestHint,
  studentQuestion,
  explainAnswer,
  socraticFeedback,
  status,
  noResult,
}
